/**
 * The client half of campaign sync.
 *
 * `src/services/sync.ts` queues WARBANDS — one entry per warband id, because a
 * warband is pushed whole and the last state is the only one that matters.
 * Campaigns cannot work that way. A campaign is edited by several people at
 * once, so two edits to one territory are two facts and not one later state,
 * and a queue keyed by entity would collapse them into a last-writer-wins blob
 * before the request was even made.
 *
 * So this queue is keyed by OPERATION. Each entry is one thing somebody did,
 * with the id it will be acknowledged under and the version it was made
 * against. See `docs/CAMPAIGN-SYNC.md`.
 */
import type { CampaignHouseRules } from '@/types/campaign';

/** What one queued operation looks like, matching the endpoint's schema. */
export type CampaignOp =
  | {
      kind: 'campaign.settings';
      opId: string;
      campaignId: string;
      baseVersion: number;
      data: {
        name?: string;
        currentTurn?: number;
        currentGame?: number;
        maxWarbandDucats?: number;
        gloryVictoryThreshold?: number;
        framework?: 'classic' | 'carcass-front';
        houseRules?: CampaignHouseRules;
      };
    }
  | {
      kind: 'territory.perk';
      opId: string;
      campaignId: string;
      entityId: string;
      baseVersion: number;
      data: { perk: string };
    }
  | {
      kind: 'territory.claim';
      opId: string;
      campaignId: string;
      entityId: string;
      baseVersion: number;
      data: { warbandId: string };
    };

export interface SyncConflict {
  opId: string;
  /** The server's copy of the entity, for the app to show. */
  server: unknown;
}

/**
 * `v1` in the key, like the warband outbox.
 *
 * A queue whose shape changes under a client that still has entries in it is a
 * queue that throws on read, and the entries it throws away are exactly the
 * edits it existed to protect. A new shape gets a new key.
 */
const OUTBOX_KEY = 'tc_campaign_outbox_v1';

/*
  Checked per call, not captured at module load.

  A module-level `const` freezes the answer at import time, which is wrong
  twice: it is evaluated during server rendering and never revisited, and it
  makes the queue untestable without a DOM because the module decides it has
  no storage before a test can give it one.
*/
const isBrowser = () => typeof window !== 'undefined' && !!window.localStorage;

function read(): CampaignOp[] {
  if (!isBrowser()) return [];
  try {
    const raw = window.localStorage.getItem(OUTBOX_KEY);
    const parsed = raw ? JSON.parse(raw) : [];
    return Array.isArray(parsed) ? (parsed as CampaignOp[]) : [];
  } catch {
    return [];
  }
}

function write(ops: CampaignOp[]): void {
  if (!isBrowser()) return;
  try {
    window.localStorage.setItem(OUTBOX_KEY, JSON.stringify(ops));
  } catch {
    /* A full quota must not take the edit down with it: the change is already
       in the local campaign, and losing the queue costs a delayed push. */
  }
}

/**
 * A new operation id.
 *
 * Generated by the CLIENT, before the first attempt, and reused on every
 * retry — that is what lets the server recognise a repeat. An id minted per
 * attempt would make each retry a new operation, which is the bug this
 * protocol exists to prevent.
 */
export const newOpId = (): string =>
  (isBrowser() && window.crypto?.randomUUID)
    ? window.crypto.randomUUID()
    : `op-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

export const campaignOutbox = {
  pending: (): CampaignOp[] => read(),
  size: (): number => read().length,

  /**
   * Queue an operation. Order is preserved, because a batch's operations may
   * touch the same entity and the second only makes sense after the first.
   */
  add(op: CampaignOp): void {
    const ops = read();
    /* Re-queuing an id already waiting is a no-op rather than a duplicate: it
       would be sent twice, and the second would come back `skipped` anyway. */
    if (ops.some((o) => o.opId === op.opId)) return;
    ops.push(op);
    write(ops);
  },

  /** Remove operations the server has accounted for. */
  clear(opIds: string[]): void {
    if (!opIds.length) return;
    const gone = new Set(opIds);
    write(read().filter((o) => !gone.has(o.opId)));
  },

  /** Everything queued for one campaign, oldest first. */
  forCampaign(campaignId: string): CampaignOp[] {
    return read().filter((o) => o.campaignId === campaignId);
  },
};

export type PushResult =
  | { ok: true; applied: string[]; skipped: string[]; conflicts: SyncConflict[] }
  | { ok: false; reason: 'offline' | 'auth' | 'server'; detail: string };

/**
 * Send everything queued for one campaign.
 *
 * **Fetch before push, and stop if the fetch fails.** An offline device that
 * pushes blind overwrites a newer cloud copy with an older one, and a fetch
 * that cannot be made is not permission to write — it is the absence of the
 * information the push needed. The caller does the fetch; this refuses to run
 * without evidence it succeeded.
 *
 * **Applied and skipped both clear the queue.** `skipped` means the server had
 * already applied that operation, which is the retry working as designed.
 *
 * **Conflicts stay queued and are returned.** They are not resolved here:
 * `docs/DATABASE.md`'s rule is that a wrong answer is worse than a visible
 * question, and merging two people's edits without asking is a wrong answer
 * that nobody sees. The app shows them; the player decides.
 *
 * **Nothing is cleared when the request fails.** The distinction that matters
 * is between "the server said no" and "the server was not reached", and only
 * the first is an answer.
 */
export async function pushCampaignOps(
  campaignId: string,
  { fetched }: { fetched: boolean },
): Promise<PushResult> {
  if (!fetched) {
    return {
      ok: false,
      reason: 'offline',
      detail: 'The campaign could not be fetched, so nothing was pushed. '
            + 'Pushing without it would overwrite a newer copy with an older one.',
    };
  }

  const ops = campaignOutbox.forCampaign(campaignId);
  if (!ops.length) return { ok: true, applied: [], skipped: [], conflicts: [] };

  let res: Response;
  try {
    res = await fetch('/api/campaigns/sync', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      /* `campaignId` is stripped: the endpoint takes it once, at the top, and
         an operation carrying its own would be a second place to disagree. */
      body: JSON.stringify({
        campaignId,
        ops: ops.map(({ campaignId: _drop, ...op }) => op),
      }),
    });
  } catch (e) {
    return { ok: false, reason: 'offline', detail: e instanceof Error ? e.message : 'Network error.' };
  }

  if (res.status === 401 || res.status === 403) {
    return { ok: false, reason: 'auth', detail: 'You are not allowed to change that campaign.' };
  }
  if (!res.ok) {
    /* Left queued. A 500 is not the server saying no, it is the server not
       answering, and discarding the queue would lose the work. */
    return { ok: false, reason: 'server', detail: `The server returned ${res.status}.` };
  }

  const body = await res.json() as {
    applied?: string[]; skipped?: string[]; conflicts?: SyncConflict[];
  };
  const applied = body.applied ?? [];
  const skipped = body.skipped ?? [];
  const conflicts = body.conflicts ?? [];

  campaignOutbox.clear([...applied, ...skipped]);
  return { ok: true, applied, skipped, conflicts };
}
